etudiant/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.saisie_matricule, name='saisie_matricule'),
    # path('Reclamer/', views.Reclamer, name='Reclamer'),
    path('login/', views.auth_etudiant, name='login'),
    # path('fait/', views.faitreclamer, name='reclamer'),  
    path('reclamation/create/', views.create_reclamation, name='create_reclamation'),
    path('reclamation/success/', views.reclamation_success, name='reclamation_success'),
    path('logout/', views.logout_etudiant, name="logout_etudiant"),
        
    path('profil/', views.profil_etudiant, name='profil_etudiant'),

]

siteISCAE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('etudiant.urls')),
    path('agent_scolarite/', include('agent_scolarite.urls')),

]
# Ajouter les URL pour servir les fichiers média en mode développement
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

etudiant/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from django.utils import timezone

# Create your models here.

class Departement(models.Model):
    id_departement = models.CharField(max_length= 25,primary_key=True)
    nom_departement = models.CharField(max_length=40)
    responsable_departement = models.CharField(max_length=40)

class Filiere(models.Model):
    idF = models.CharField(max_length= 25,primary_key=True)
    nom = models.CharField(max_length=40)
    date_creation = models.DateField()
    domain = models.CharField(max_length=40)
    departement = models.ForeignKey(Departement, on_delete=models.CASCADE)

class Etudiant(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    matricule = models.CharField(max_length=25, primary_key=True)
    nom = models.CharField(max_length=100, null= True)
    prenom = models.CharField(max_length=100, null= True)
    nni = models.BigIntegerField(default=0, blank=True)
    sexe = models.CharField(max_length=4)
    numero_telephone = models.BigIntegerField(default=0)
    filiere = models.ForeignKey('Filiere', on_delete=models.CASCADE, default='')


class AgentDeScolarite(models.Model):
    id_agent_scolarite = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nom = models.CharField(max_length=100, null= True)
    prenom = models.CharField(max_length=100, null= True)
    numero_telephone = models.IntegerField()
    poste_agent_scolarite = models.CharField(max_length=255)

class AutorisationDeReclamation(models.Model):
    OUVERT = 'OU'
    FERME = 'FE'
    EXPIRE = 'EX'
    ETAT_CHOICES = [
        (OUVERT, 'Ouvert'),
        (FERME, 'Fermé'),
        (EXPIRE, 'Expiré'),
    ]
    id_autorisation = models.AutoField(primary_key=True)
    date_expiration = models.DateTimeField(default=timezone.now)
    date_autorisation = models.DateTimeField(default=timezone.now)
    AgentDeScolarite = models.ForeignKey(AgentDeScolarite, on_delete=models.CASCADE)
    Etat = models.CharField(max_length=2, choices=ETAT_CHOICES, default=OUVERT)

class Niveau(models.Model):
    id_niveau = models.CharField(max_length= 25,primary_key=True)
    niveau = models.CharField(max_length=20)

class Semestre(models.Model):
    id_semestre = models.CharField(max_length= 25,primary_key=True)
    Semestre = models.CharField(max_length=25)
    niveau_obj = models.ForeignKey(Niveau, on_delete=models.CASCADE)


class Matiere(models.Model):
    code = models.CharField(max_length= 25,primary_key=True)
    titre = models.CharField(max_length=30)
    credit = models.IntegerField()
    filiere = models.ForeignKey(Filiere, on_delete=models.CASCADE)
    Semestre = models.ForeignKey(Semestre, on_delete=models.CASCADE)
    

class Reclamation(models.Model):
    id_reclamation = models.AutoField(primary_key=True)
    contenu = models.TextField()
    preuve_reclamation = models.FileField(null= True, upload_to='documents/reclamations/', validators=[FileExtensionValidator(allowed_extensions=['pdf','png','jpg'])])
    status = models.CharField(max_length=30)
    type = models.CharField(max_length=30, null=True)
    date_reclamation = models.DateField()
    etudiant = models.ForeignKey(Etudiant, on_delete=models.CASCADE)
    Matiere = models.ForeignKey(Matiere, on_delete=models.CASCADE)

class Notification(models.Model):
    id_notification = models.AutoField(primary_key=True)
    contenu = models.TextField()
    date_notification = models.DateField()
    delai = models.IntegerField()
    reclamation = models.ForeignKey(Reclamation, on_delete=models.CASCADE)
    agent_scolarite = models.ForeignKey(AgentDeScolarite, on_delete=models.CASCADE)

class AnneeUniv(models.Model):
    id_annee_univ = models.CharField(max_length= 20,primary_key=True)
    annee_univ = models.CharField(max_length=20)

class Inscription(models.Model):
    id_inscription = models.AutoField(primary_key=True)
    date_inscription = models.DateTimeField()
    etudiant = models.ForeignKey(Etudiant, on_delete=models.CASCADE)
    niveau = models.ForeignKey(Niveau, on_delete=models.CASCADE)
    annee_univ = models.ForeignKey(AnneeUniv, on_delete=models.CASCADE)

class ResultatParMatiere(models.Model):
    id_res_element = models.AutoField(primary_key=True)
    note_cc = models.FloatField()
    note_ex = models.FloatField()
    note_finale = models.FloatField()
    note_rattrapage = models.FloatField()
    validation = models.CharField(max_length=40)
    etudiant = models.ForeignKey(Etudiant, on_delete=models.CASCADE)
    matiere = models.ForeignKey(Matiere, on_delete=models.CASCADE)
    annee_universitaire = models.ForeignKey(AnneeUniv, on_delete=models.CASCADE)

class ResultatParMoyenGeneral(models.Model):
    id_res_par_moy_g = models.AutoField(primary_key=True)
    id_annee_diplome = models.CharField(max_length=40)
    moy_g = models.FloatField()
    etudiant = models.ForeignKey(Etudiant, on_delete=models.CASCADE)
    semestre = models.ForeignKey(Semestre, on_delete=models.CASCADE)
    annee_univ = models.ForeignKey(AnneeUniv, on_delete=models.CASCADE)

etudiant/forms.py
from django import forms
from .models import Etudiant
from django import forms
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import User
class ConnexionForm(forms.Form):
    email = forms.EmailField(max_length=40)
    mot_de_passe = forms.CharField(max_length=40, widget=forms.PasswordInput)

    def clean_mot_de_passe(self):
        mot_de_passe = self.cleaned_data.get('mot_de_passe')
        # Ajouter ici votre validation personnalisée
        if len(mot_de_passe) < 8:
            raise forms.ValidationError("Le mot de passe doit contenir au moins 8 caractères.")
        return mot_de_passe

etudiant/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import AutorisationDeReclamation, Etudiant, Inscription, ResultatParMatiere, Semestre,Matiere, Reclamation
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login,logout 
from .forms import ConnexionForm
from .models import Etudiant
from django.shortcuts import render, redirect
from django.utils.timezone import now
from django.contrib import auth


def saisie_matricule(request):
    if request.method == 'POST':
        matricule = request.POST['matricule']
        semestre_id_selectionne = request.POST.get('semestre', None)
        try:
            etudiant = Etudiant.objects.get(matricule=matricule)
            inscription = Inscription.objects.get(etudiant=etudiant)
            
            if semestre_id_selectionne:
                # Récupérer le nom du semestre sélectionné
                semestre_selectionne = Semestre.objects.get(id_semestre=semestre_id_selectionne).Semestre
                # Logique pour filtrer les résultats en fonction du semestre sélectionné
                resultats = ResultatParMatiere.objects.filter(etudiant=etudiant, matiere__Semestre=semestre_id_selectionne)
                semestre_apres_selection = ResultatParMatiere.objects.filter(etudiant=etudiant)
                semestres = set(resultat.matiere.Semestre for resultat in semestre_apres_selection)
            else:
                # Récupérer tous les résultats de l'étudiant
                resultats = ResultatParMatiere.objects.filter(etudiant=etudiant)
                semestres = set(resultat.matiere.Semestre for resultat in resultats)
                semestre_selectionne = None

            autorisations_ouvertes = AutorisationDeReclamation.objects.filter(Etat='OU')
             # Vérifier s'il y a des autorisations ouvertes
            autorisation_existante = True if autorisations_ouvertes else False
            context = {
                'nom': etudiant.user.first_name,
                'prenom': etudiant.user.last_name,
                'niveau': inscription.niveau.niveau,
                'matricule': matricule,
                'filiere' : etudiant.filiere.nom,
                'resultats': resultats,
                'semestres': semestres,
                'semestre_selectionne' : semestre_selectionne,
                'annee_univ' : inscription.annee_univ.annee_univ,
                'autorisations_ouvertes': autorisations_ouvertes, 
                'autorisation_existante': autorisation_existante
            }
            return render(request, 'infos_etudiant.html', context)
        except Etudiant.DoesNotExist:
            return render(request, 'etudiant_non_trouve.html')
    else:
        return render(request, 'saisie_matricule.html')

def auth_etudiant(request):
    error_message = None

    if request.method == 'POST':
        email = request.POST.get('email')
        mot_de_passes = request.POST.get('mot_de_passe')

        user = authenticate(request, username=email, password=mot_de_passes)
        if user is not None:
            login(request, user)
            # Récupérer l'URL à laquelle l'utilisateur tentait d'accéder avant la connexion
            redirect_to = request.GET.get('next', 'profil_etudiant')
            # Rediriger l'utilisateur vers cette URL ou vers la page de profil étudiant par défaut
            return redirect(redirect_to)
        else:
            error_message = "Adresse e-mail ou mot de passe incorrect."

    return render(request, 'AuthEtudiant.html', {'error_message': error_message})



@login_required
def create_reclamation(request):
    autorisations_ouvertes = AutorisationDeReclamation.objects.filter(Etat='OU')

    if not autorisations_ouvertes.exists():
        # Si une autorisation de réclamation est ouverte, rediriger l'utilisateur
        return redirect('saisie_matricule') 
   # Récupérer l'étudiant authentifié
    etudiant = request.user.etudiant

    # Récupérer le dernier semestre du niveau de l'étudiant
    dernier_semestre = Semestre.objects.filter(niveau_obj=etudiant.inscription_set.first().niveau).latest('id_semestre')

    if request.method == 'POST':
        # Récupérer les données du formulaire
        contenu = request.POST.get('contenu')
        preuve_reclamation = request.FILES.get('preuve_reclamation')
        matiere_id = request.POST.get('Matiere')

        # Créer la réclamation
        reclamation = Reclamation.objects.create(
            contenu=contenu,
            preuve_reclamation=preuve_reclamation,
            etudiant=etudiant,
            date_reclamation=now(),
            status="en attente",
            Matiere_id=matiere_id
        )
        # Associer la matière à la réclamation
        if matiere_id:
            matiere = Matiere.objects.get(code=matiere_id)
            reclamation.Matiere = matiere
            reclamation.save()

        return redirect('reclamation_success')  # Rediriger vers une page de succès

    # Récupérer les matières du dernier semestre du niveau de l'étudiant
    matieres_semestre = Matiere.objects.filter(Semestre=dernier_semestre, filiere=etudiant.filiere)

    # Si la méthode de la requête n'est pas POST, rendre le template avec un formulaire vide
    return render(request, 'reclamation_form.html', {'matieres': matieres_semestre})
@login_required
def reclamation_success(request):
    return render(request, 'reclamation_success.html')


# ### Profile

@login_required
def profil_etudiant(request):
    # Récupérer l'utilisateur connecté
    user = request.user

    # Récupérer le profil de l'étudiant s'il existe
    try:
        etudiant = Etudiant.objects.get(user=user)
    except Etudiant.DoesNotExist:
        etudiant = None

    # Récupérer les réclamations de l'étudiant s'il existe
    if etudiant:
        reclamations = Reclamation.objects.filter(etudiant=etudiant)
    else:
        reclamations = None

    context = {
        'etudiant': etudiant,
        'reclamations': reclamations
    }

    return render(request, 'profil_etudiant.html', context)

def logout_etudiant(request):
    if request.method == 'POST':
        auth.logout(request)
    return redirect('saisie_matricule')

etudiant/templates/AuthEtudiant.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}
<div class="container">
  <div class="d-flex justify-content-center inline">
    <div class="box1">
      <div class="notes2">
        <div class="info-item d-flex justify-content-center">
          <div class="">
          <img
            src="{% static 'staticEtudiant/img/logo-iscae.png' %}"
            alt=""
            width="170"
            height="170"

          />
          </div>
        </div>
        <hr>
        {% if error_message %}
        <p style="color: red">{{ error_message }}</p>
        {% endif %}
        <form method="post">
          {% csrf_token %} 
          <input
            type="email"
            id="email"
            name="email"
            required
            placeholder="Adresse e-mail:"
          />
          <input
            type="password"
            id="mot_de_passe"
            name="mot_de_passe"
            required
            placeholder="Mot de passe:"
          />
          <input type="submit" value="Se connecter" class="end" />
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

etudiant/templates/Reclamer.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mt-5">
    <form method="post" enctype="multipart/form-data" onsubmit="toggleUpload()">
        {% csrf_token %}
        <div class="mb-3" id="fileInput">
            <label for="fileInput" class="form-label">Choose file or take a photo</label>
            <input type="file" class="form-control"  accept="image/*, .pdf" name="preuve_reclamation" style="display: none;">
        </div>
        <div class="mb-3">
            <label for="messageText" class="form-label">Your Message</label>
            <textarea class="form-control" id="messageText" rows="3" name="contenu"></textarea>
        </div>
        <div class="mb-3">
            <label for="matiere">Matière concernée:</label><br>
            <select id="matiere" name="matiere">
                {% for matiere in matieres %}
                <option value="{{ matiere.code }}">{{ matiere.titre }}</option>
                {% endfor %}
            </select><br>
        </div>
        <div class="mb-3">
            <label for="type_examen">Type d'examen:</label><br>
            <input type="radio" id="cc" name="type_examen" value="CC" onchange="toggleUpload()">
            <label for="cc">Contrôle Continu</label><br>
            <input type="radio" id="examen" name="type_examen" value="Examen">
            <label for="examen">Examen</label><br>
        </div>
        
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        function toggleUpload() {
            var ccCheckbox = document.getElementById('cc');
            var fileInput = document.getElementById('fileInput');
    
            if (ccCheckbox.checked) {
                fileInput.style.display = 'block';
            } else {
                fileInput.style.display = 'none';
            }
        }
    </script>
</div>
{% comment %} <a href="{% url 'logout' %}">Déconnexion</a> {% endcomment %}
{% endblock %}

etudiant/templates/etudiant_non_trouve.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h2>Étudiant non trouvé</h2>
    <p>L'étudiant avec ce Mainatricule n'est pas dans la base de données.</p>
</div>
{% endblock %}

etudiant/templates/infos_etudiant.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Informations de l'étudiant {% endblock %}

{% block content %}
<div class="d-flex justify-content-center inline">
  <div class="notes">
    <form method="post" id="form-etudiant">
      {% csrf_token %}
      <input
        type="text"
        id="matricule"
        name="matricule"
        class="form-control my-2"
        placeholder="Veuillez saisir votre matricule:"
        value="{{ matricule }}"
      />

      <input type="submit" value="Confirmer" class="btn btn-primary my-2" />
      &nbsp;&nbsp;&nbsp;
      <select name="semestre" id="semestre" class="form-control my-2">
        <option value="">Semestre</option>
        {% for semestre in semestres|dictsort:"Semestre" %}
        <option value="{{ semestre.id_semestre }}">
          {{ semestre.id_semestre }}
        </option>
        {% endfor %}
      </select>
    </form>
  </div>
</div>
<br />

<div class="cont-marg-bottom">
  <div class="container">
    <h5>Informations de l'étudiant :</h5>
    <div id="imprimer">
      <hr>
      <span>Nom et prénom: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;<strong>{{ nom }} {{ prenom }}</strong></span><br />
      <span>Numéro d'inscription :&nbsp;&nbsp;<strong>{{ matricule }} </strong></span><br />
      <span>Année Académique :&nbsp;&nbsp; <strong>{{ annee_univ }} </strong></span><br />
      <span>Filière: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>{{ niveau }} {{ filiere }}</strong></span><br />
      <hr>

      {% if semestre_selectionne %}
      <div class="result" id="resultats-section">
        <span>Semestre : <strong>{{ semestre_selectionne }} </strong></span><br />
        <div class="resultMat">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>Matière / Module</th>
                <th>Contrôle Continu</th>
                <th>Contrôle Finale</th>
                <th>Note Finale</th>
                <th>Credit</th>
                <th>Décisions</th>
              </tr>
            </thead>
            <tbody>
              {% for resultat in resultats %}
              {% ifchanged resultat.matiere.Module.module %}
              <tr>
                <th class="th2"><strong>{{ resultat.matiere.Module.module }}</strong></th>
                <td colspan="3"><strong>13.5</strong></td>
                <td><strong>7</strong></td>
                <td>
                  <strong>
                    {% for module, decision in decision_du_module.items %}
                    {% if module == resultat.matiere.Module.module %}
                      {% if decision == 'Rattrapage' %}
                      Rattrapage
                      {% elif decision == 'Valide' %}
                      validé
                      {% endif %}
                    {% endif %}
                    {% endfor %}
                  </strong>
                </td>
              </tr>
              {% endifchanged %}
              <tr>
                <td class="mat-num"><strong>{{ resultat.matiere.titre }}</strong></td>
                <td class="resu-num">{{ resultat.note_cc }}</td>
                <td class="resu-num">{{ resultat.note_ex }}</td>
                <td class="resu-num">{{ resultat.note_finale }}</td>
                <td class="resu-num">{{ resultat.matiere.credit }}</td>
                <td class="mat-num">{{ resultat.validation }}</td>
              </tr>
              {% endfor %}
              <tr colspan="3">
                <th colspan="4"><strong>Moyenne Générale</strong></th>
                <th>Credit</th>
                <th colspan="2">Décision</th>
              </tr>
            </tbody>
            {% for resultat in resultats_moyen_general %}
            <tr>
              <td colspan="4" class="resu-num"><strong>{{ resultat.moy_g }}</strong></td>
              <td class="resu-num"><strong>{{ credits_semestre }}</strong></td>
              <td colspan="2" class="resu-num"><strong>{{ decision }}</strong></td>
            </tr>
            {% endfor %}
          </table>
        </div>
      </div>

      <!-- Adjust button placement here -->
      <div class="d-flex justify-content-end mt-4">
        {% if autorisation_existante %}
        <a href="{% url 'create_reclamation' %}" class="btn btn-primary mr-2">Faire une réclamation</a>
        {% endif %}
        
        <button onclick="imprimerPage()" class="btn btn-primary">Imprimer</button>
      </div>
    </div>
  </div>
  {% endif %}
</div>

<script>
document.getElementById("semestre").addEventListener("change", function() {
  var selectedSemestre = this.value;
  var resultatsSection = document.getElementById("resultats-section");

  if (selectedSemestre) {
    resultatsSection.style.display = "block";
  } else {
    resultatsSection.style.display = "none";
  }
});

document.getElementById("semestre").addEventListener("change", function() {
  document.getElementById("form-etudiant").submit();
});

function imprimerPage() {
  var contenuImprimer = document.getElementById("imprimer").innerHTML;
  var fenetreImprimer = window.open('', '', 'height=400,width=600');
  fenetreImprimer.document.write('<html><head><title>Impression</title>');
  fenetreImprimer.document.write('<style>');
  fenetreImprimer.document.write('table { width: 100%; border: 1px solid black; border-collapse: collapse; }');
  fenetreImprimer.document.write('body {padding-top:100px; padding-left:20px; padding-right:20px; }');
  fenetreImprimer.document.write('td, th { text-align: center; border: 1px solid black; padding: 8px; }');
  fenetreImprimer.document.write('th { background-color: #C0C0C0; color: #333; }');
  fenetreImprimer.document.write('th.th2 { background-color: #F0F0F0; color: #666; }');
  fenetreImprimer.document.write('</style>');
  fenetreImprimer.document.write('</head><body>');
  fenetreImprimer.document.write('<style>@media print { #en-tete { position: fixed; top: 0; left: 0; right: 0; } }</style>');
  fenetreImprimer.document.write('<div id="en-tete"><img src="https://www.mesrs.gov.mr/sites/default/files/2022-01/ISCAE.jpg" alt="En-tête" style="width: 100%;"></div>');
  fenetreImprimer.document.write(contenuImprimer);
  fenetreImprimer.document.write('</body></html>');
  fenetreImprimer.document.close();
  fenetreImprimer.print();
}
</script>

{% endblock %}

etudiant/templates/profil_etudiant.html
{% extends 'base.html' %}
{% load static %} 
{% block title %} Profile de l'étudiant {% endblock %}

{% block content %}
<main id="main">
    <!-- ======= Portfolio Details Section ======= -->
    <section id="portfolio-details" class="portfolio-details">
      <div class="container" data-aos="fade-up">

        <div class="row justify-cotent-between gy-4 mt-4">

          <div class="col-lg-8">
            <div class="portfolio-description">
              <div class="testimonial-item mb-4">
                
                <img src="{% static 'img/logo-iscae.png' %}" alt="" style="max-width: 150px;"> <!-- Adjusted size here -->
                <h3>{{ etudiant.user.username }}</h3>
                <h4>{{ etudiant.filiere.nom }}</h4>
           
              </div>
              
             
              
              <span><strong>Matricule:</strong> {{ etudiant.matricule }}</span></br>
              <span><strong>NNI:</strong> {{ etudiant.nni }}</span></br>
              <span><strong>Sexe:</strong> {{ etudiant.sexe }}</span></br>
              <span><strong>Numéro de téléphone:</strong> {{ etudiant.numero_telephone }}</span></br>

             
            </div>
          </div>

          <div class="col-lg-3">
            <div class="portfolio-info">
              <h3>Réclamations</h3>
              <ul>
                  {% for reclamation in reclamations %}
                  <li>
                      <spam><strong>Matière:</strong> {{ reclamation.Matiere.titre }}<br></span>
                      <strong>Statut:</strong>
                      {% if reclamation.status == 'en attente' %}
                      <span class="badge bg-warning text-dark">{{ reclamation.status }}</span>
                       {% elif reclamation.status == 'Refusée' %}
                       <span class="badge bg-danger text-dark">{{ reclamation.status }}</span>
                       {% elif reclamation.status == 'Acceptee' %}
                       <span class="badge bg-success text-dark">{{ reclamation.status }}</span>
                       {% elif reclamation.status == 'En cours' %}
                       <span class="badge bg-info text-dark">{{ reclamation.status }}</span>
                       {% elif reclamation.status == 'Terminée' %}
                       <span class="badge bg-success text-dark">{{ reclamation.status }}</span>
                       {% endif %}
                       
                       <br>
                  </li>
                  {% endfor %}
              </ul>
            </div>
          </div>

        </div>

      </div>
    </section><!-- End Portfolio Details Section -->

  </main><!-- End #main -->
{% endblock %}

etudiant/templates/reclamation_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    /* Custom styles for mobile buttons */
    @media (max-width: 768px) {
        .thin-button {
            padding: 6px 10px; /* Smaller padding for thinner appearance */
            font-size: 10px; /* Smaller font size for mobile */
            line-height: 1.2; /* Adjust line height to fit the design */
        }
        
        .button-container button {
            padding: 6px 3px; /* Reduced padding for a thinner button */
            font-size: small; /* Smaller font size for readability */
            margin-bottom: 2px; /* Reduced margin to stack closely */
            width: 50%; /* Full width for easier touch */
        }
    }

    /* Additional styling for all screen sizes */
    .button-container button {
        margin-bottom: 10px; /* Space between buttons when stacked */
        width: 100%; /* Ensuring full width for smaller screens */
    }
</style>

<script>
    function toggleUpload(type) {
        var fileInput = document.getElementById('fileInput');
        if (type === 'cc') {
            fileInput.style.display = 'block';
        } else {
            fileInput.style.display = 'none';
        }
    }
</script>

<section id="contact" class="contact">
    <div class="container" data-aos="fade-up">
        <div class="row gx-lg-0 gy-4">
            <div class="col-lg-4">
                <div class="info-container d-flex flex-column align-items-center justify-content-center">
                    <div class="info-item d-flex">
                        <i class="bi bi-envelope flex-shrink-0"></i>
                        <div>
                            <h4>Alert:</h4>
                            <p>"Attention ! Soumettre de fausses réclamations est strictement interdit et entraînera des sanctions disciplinaires."</p>
                        </div>
                    </div><!-- End Info Item -->
                </div>
            </div>

            <div class="col-lg-8">
                <form id="reclamation-form" method="post" role="form" class="php-email-form" enctype="multipart/form-data" onsubmit="toggleUpload()">
                    {% csrf_token %}

                    <div class="row">
                        <div class="col-md-6 form-group mt-3 mt-md-0">
                            <!-- Additional inputs can be placed here -->
                        </div>
                    </div>
                    <div id="autreReclam">
                        <div class="form-group mt-3">
                            <label for="messageText" class="form-label">Description</label>
                            <textarea class="form-control" type="text" id="id_contenu" rows="3" name="contenu" required></textarea>
                        </div>
                        <div class="form-group mt-3">
                            <label for="matiere">Matière concernée:</label><br>
                            <select id="id_Matiere" class="form-control" name="Matiere" required>
                                <option value="" disabled selected>Choisissez une matière</option>
                                {% for matiere in matieres %}
                                <option value="{{ matiere.code }}">{{ matiere.titre }}</option>
                                {% endfor %}
                            </select><br>
                        </div>
                        <div class="form-group mb-3">
                            <label for="type_examen">Type d'examen:</label><br>
                            <input type="radio" id="cc" name="type_reclamation" value="Devoir" onchange="toggleUpload('cc')">
                            <label for="cc">Contrôle Continu</label><br>
                            <input type="radio" id="examen" name="type_reclamation" value="Examen" onchange="toggleUpload('examen')">
                            <label for="examen">Examen</label><br>
                        </div>
        
                        <div class="form-group mb-3" id="fileInput" style="display: none;" aria-required="">
                            <label for="cc">Note exacte: </label><br>
                            <input type="number" class="form-control" name="note_exacte"></br>
                            <label for="fileInput" class="form-label">Choisir un fichier ou un photo</label>
                            <input type="file" class="form-control" accept="image/*, .pdf" name="preuve_reclamation" id="preuve_reclamation">
                        </div>
                    </div>
                    <div class="text-center button-container">
                        <button type="submit" name="action" value="reclamer" class="thin-button">Reclamer</button>
                        <button type="submit" name="action" value="reclamer_et_ajouter" class="thin-button">Reclamer et Ajouter Autre</button>
                    </div>
                </form>
            </div><!-- End Contact Form -->
        </div>
    </div>
</section>
{% endblock %}
{% block scripts %}
    {% comment %} <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> {% endcomment %}
{% endblock %}

etudiant/templates/reclamation_success.html
{% extends 'base.html' %}
{% block content %}
<h2>Reclamation submitted successfully!</h2>
{% endblock %}